# Site settings
title: Randy's Blog
email: randypriv#gmail.com
description: JavaScripter，转Android开发。希望用技术影响世界。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://djyde.github.io" # the base hostname & protocol for your site
twitter_username: iamRandy
github_username:  djyde

# Build settings
markdown: kramdown
